Ayurveda/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ayurvedasite.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ayurvedasite/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
app_name='ayurvedasite'
urlpatterns=[
path('', views.home_page, name='home_page'),
path('intro/', views.intro_page, name='intro_page'),
path('logout/', auth_views.LogoutView.as_view(template_name='ayurvedasite/home.html'), name='logout'),
path('comment/', views.home_page, name='home_page'),
path('symptoms/',views.symptoms,name='symptoms'),


]

ayurvedasite/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Symptoms(models.Model):
	name=models.CharField(max_length=100)
	image=models.ImageField(upload_to='images/', default='static/ayurvedasite/images/no.png')
	description=models.TextField(max_length=500)
	causes=models.TextField(max_length=500)
	symptom=models.TextField(max_length=500)
	remedy=models.TextField(max_length=500)
	link=models.URLField(max_length=100)

	def __str__(self):  
		return self.name


		
class Comment(models.Model):
	user=models.CharField(max_length=200)
	email=models.EmailField()
	text=models.TextField(max_length=500)
	created_date=models.DateTimeField(default=timezone.now())
	approved_comment=models.BooleanField(default=False)

	def approve(self):
		self.approved_comment=True
		self.save()

	def ___str__(self):

		return self.text

ayurvedasite/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields = ('user','text','email')

ayurvedasite/views.py
from django.shortcuts import render, redirect
from .forms import CommentForm
from .models import Comment, Symptoms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
def home_page(request):
	if request.method=='POST':
		form=CommentForm(request.POST)
		if form.is_valid():
			comment=form.save(commit=False)
			comment.save()
			form=CommentForm()
	else:
		form = CommentForm()
	comments=Comment.objects.all().order_by('-id')
	return render(request, 'ayurvedasite/home.html', {'comments':comments, 'form':form})

def intro_page(request):
	return render(request, 'ayurvedasite/intro.html',{})

	
def symptoms(request):
	symptoms_list =Symptoms.objects.all().order_by('id')
	paginator = Paginator(symptoms_list,2,allow_empty_first_page=False)
	page=request.GET.get('page',1)
	sym=paginator.page(page)
	return render(request, 'ayurvedasite/symptoms.html', {'sym': sym})
	

ayurvedasite/templates/ayurvedasite/add_comment.html
{% extends 'ayurvedasite/base.html' %}
{% load static %}

{% block content %}
<div class="forms">
                <div class="row">
                    <div class="col-12 col-sm-6">
                <div class="form-group">
                   


    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    



            </form>
        </div>
    </div></div></div>
            
 {% endblock %}           

ayurvedasite/templates/ayurvedasite/base.html
{% load static %}

<html>

<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'ayurvedasite/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
.jumbotron{
        background-image:url({% static 'ayurvedasite/images/download.jpeg' %});
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        height: 500;
    }
</style>
	<title>Ayurveda:Healing Power of Nature</title>
</head>
<body>

	<div class="header bg-success">
		<div id ="imgblock"><img src="{% static 'ayurvedasite/images/logo.jpeg' %}" class="float-left rounded-circle" id="imlogo"></div>
		<div class="text-center mt-4" id="text-heading"><b><i><h1 class="text-white h1" id="heading">AYURVEDA<br>
		</h1><h1 class="text-white" h1>The Healing Power Of Nature</i></b>

	</div>
</div>
<nav class="navbar navbar-expand-md navbar-dark bg-info mt-4">
	<div class="container">
		<a class="navbar brand mr-4" href="#"><strong>AYURVEDA</strong></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarToggle">
			<div class="navbar-nav mr-auto">
				<a class=" nav-item nav-link" href="{% url 'ayurvedasite:home_page' %}"><strong>HOME</strong></a>
			</div>
			<div class="collapse navbar-collapse" id="navbarToggle">
			<div class="navbar-nav mr-auto">
				<a class=" nav-item nav-link mr-1" href="{% url 'ayurvedasite:intro_page' %}" ><strong>HISTORY</strong></a>
			</div>
			<div class="collapse navbar-collapse" id="navbarToggle">
			<div class="navbar-nav mr-auto">
				<a class=" nav-item nav-link" href="{% url 'ayurvedasite:symptoms'%}"><strong>DISEASES AND REMEDIES</strong></a>
			</div>

			<div class="navbar-nav">
				{% if user.is_authenticated %}
	<a href="{% url 'ayurvedasite:logout' %}"><button type="button" class="btn btn-success"><strong>LOGOUT</strong></button></a>
					
				{% else %}
				<a href="{% url 'social:begin' 'google-oauth2' %}"><button type="button" class="btn btn-danger m-1">Google+</button></a>
				
				{% endif %}
			
	</div></div></div></nav>
<section id="section-top" class="jumbotron jumbotron-fluid text-white d-flex justify-content-center align-items-center">
<div class="container text-center">
	<mark>
	<div class="text-center text-white mt-5 h1" id="top"><b><i>leave your drugs in the chemist's pot <br>if you can heal the patient with food.</i></b></div></mark>
	</div>
            </section>

    

       {% block content %}
       {% endblock %}
       <div class="bg-dark">
       	
       
       	<div class="container"><br><h3 class="text-white">ABOUT US</h3>
       		<p class="text-white"> Ayurveda was founded with the mission of 'taking Ayurveda to every home'. Our objective of making people happy and healthy through authentic Ayurvedic treatment delivered to the growing ailments and disorders such as diabetes, arthritis, asthma, obesity, hypertension, spondylitis, piles, skin problems, sexual disorders, etc. Most of these diseases affecting the global community today do not have an effective treatment available in modern medicine.
</p>
       	</div>
       	 
       	<div class="col-12 col-sm-6 col-lg-3">
						
						<address>
							<<h3 class="text-white">ADDRESS:</h3>
							<p class="text-white">350 5th avenue<br>
							India NY 10118<br>
							<i class="fa fa-phone fa-fw" aria-hidden="true"></i>
							<span class="sr-only">Telephone</span><a href="tel:+1217363600">(212) 7363600</a><br>
							<i class="fa fa-inbox fa-fw" aria-hidden="true"></i><span class="sr-only">Mail</span><a href="mailto:info@ayurveda.com">info@ayurveda.com</a></p>
						</address></div></div>
       
      
  
	</body>


</html>

ayurvedasite/templates/ayurvedasite/home.html
{% extends "ayurvedasite/base.html" %}
{% load static %}

{% block content %}


    


<div class= "p-5 m-5" id="health" >
	<h1 class="text-info text-center">Health Tips</h1>
	<ol>
		<li>Schedule a walk with a friend or co-worker. Ayurveda considers <mark>walking a tridoshic exercise</mark>: it balances all three doshas without putting excessive strain on your body. It calms the mind and nourishes the senses.</li>
		<li>Drink a <mark>glass of water</mark>. Water flushes out accumulated ama, and keeps the digestion smooth. Sipped throughout the day, water is an excellent healer.</li>
		<li>
		Sit down and close your eyes. Take a "just-for-me" break right now, right here. Disconnect from the outer world and tune in to your own self. Even if you do this for a minute, you will feel healed. Practitioners of <mark>Transcendental Meditation</mark> say their daily 20-minute sadhana helps conquer stress and increase positive energy and a sense of well-being.</li>
         <li>Sip herb tea. All-natural, caffeine-free teas prepared from nature's healing herbs are a perfect way to relax and recharge: choose from among Maharishi Ayurveda's wide range of <mark>gourmet beverages</mark> to pick the flavor and blend that suits your unique dosha type and your needs</li>
         <li><mark>Breathe deep</mark>. Mindful breathing improves the flow of oxygen and other vital nutrients to the tiniest channels of the body, giving you an instant sense of well-being.</li>
     </ol>
 </div>


        
            
            <h2 class="text-success">Comments</h2>
            <button type="button" class="btn btn-primary">Comment{{ comments|pluralize }} <span class="badge">{{comments.count }}</span></button>
            
             {% for comment in comments %}
            
                 
            <div class="media mt-5">
                <img src="https://c.disquscdn.com/next/embed/assets/img/noavatar92.7b2fde640943965cc88df0cdee365907.png" class="mr-3">
                <div class="media-body">
                	<blockquote class="blockquote">
                    <strong>{{ comment.text }}</strong><footer class="blockquote footer">  (Posted on: {{ comment.created_date }})by <p class="text-info"><small> by {{ comment.user }}</small></p></footer></div>
                </blockquote>
                </div>
                <hr>
             {% empty %}
             <p>No comments here yet:(</p>
             {% endfor %}   
                
<div class="forms">
                <div class="row">
                    <div class="col-12 col-sm-6">
                <div class="form-group">
                   


    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    



            </form>
        </div>
    </div></div></div>
            
          
{% endblock content %}

ayurvedasite/templates/ayurvedasite/intro.html
{% extends "ayurvedasite/base.html" %}
{% load static %}

{% block content %}

<h3 class="text-center text-danger mt-5" id="aa">
Rather than treating symptoms with drugs and ignoring the underlying problems, Ayurvedic medicine aims to look at the root of disease and how it’s related to a person’s thoughts, beliefs and lifestyle — in other words, a person’s “vital energy.</h3>
<div class="contain">
	<h2 class="text-center m-5 text-secondary">HISTORY AND INTRODUCTION</h2>
	<p class="m-4 h5">
History of medicine is a fascinating subject as it is a saga of man’s struggle against
disease. As the civilization advances and as the disease pattern changes, the medical science
also changes. Ayurveda is the system of medicine that evolved in India with a rationale logical
foundation and it has survived as a distinct entity from remote antiquity to the present day. The
fundamentals on which the Ayurvedic system is based are essentially true for all times and do not
change from are to age. These are based on human actors, on intrinsic causes. The origin of
Ayurveda is attributed to Atharva Veda where mention is made several diseases with their
treatments. Later, from the 6th Century BC to 7th Century AD there was systematic development
of the science and it is called Samhita period, when a number of classical works were produced
by several authors and during this period there is evidence of organized medical care.
<br>
 Ayurvedic medicine concentrates on health and wellness by harmonizing the mind, body, and spirit. You can achieve total wellness from a trained Ayurvedic practitioner through methods such as guided meditation, yoga, massage, herbal medicine, and body-specific changes in diet.
 This form of medicine categorizes three types of life forces or doshas: Vata dosha, Pitta dosha, and Kapha dosha. Each person has a combination of each life energy, but one is believed to be dominant. Identifying which life force needs to be balanced can alleviate health issues, as each dosha controls a different function in the body.</p>
 <h2 class="text-center m-5 text-secondary">BENEFITS</h2>
<h2 class="text-danger m-3">
 Reduces stress:</h3>
 <img class="m-4 rounded"  class="rounded m-5" src="{% static 'ayurvedasite/images/img1.jpeg' %}">
<br>
<p class="m-4 h5">
	
Meditation, yoga, herbal treatments, and breathing exercises are some of the many techniques that can help reduce stress and anxiety. A medical research review conducted by St. Elizabeth’s Medical Center in Massachusetts found that over the corse of 35 trials, investigating the effects of yoga, 25 trials showed significant reduction in signs of stress and anxiety. Other research says that regular yoga practice can improve autonomic nervous functions by reducing sympathetic activity, which is our fight or flight response.</p>
<h2 class="text-danger m-5">
Weight Loss Or Maintenance:</h3>
<img src="{% static 'ayurvedasite/images/img2.jpeg' %}">
<br>
<p class="m-4 h5">
While weight loss isn’t a main concern, Ayurvedic medicine promotes shedding excess weight by consuming a natural and healthy diet. A study conducted by NutriHealth System in New Delhi found that changing someone’s health diet helped clients lose weight effectively. 
</p>
<img src="{% static 'ayurvedasite/images/img3.jpeg' %}">
<h2 class="text-danger m-3">
Minimizes In class="m-4 rounded" flammation:</h3>
<br>
<p class="m-4 h5">
Inflammation can be caused by inadequate sleep, poor diet, and deficient digestion. The Ayurvedic method of healing reduces inflammation to regulate the heart system and digestive tract by eliminating waste. Consuming a combination of herbal treatments, exercise that gently boosts metabolism, and antioxidants can help lower inflammation and increase energy.
</p>
<h2 class="text-danger m-3">
Reduce Symptoms of Illness and Disease:</h3>
<img  class="m-4 rounded" src="{% static 'ayurvedasite/images/img9.jpeg' %}">
<br>
<p class="m-4 h5">
Eating an illness-specific diet, getting sun exposure, and breathing in and out can help the person eat better and treat symptoms of illness. Metals like iron are thought to have healing properties to keep diseases away and reduce the chances of getting sick. Some supplements claiming to be approved by Ayurveda may contain toxic metals, so proceed with caution before purchasing them, especially online!</p>
<h2 class="text-danger m-3">
Cleanses The Body:</h3>
<img  class="m-4 rounded" src="{% static 'ayurvedasite/images/img4.jpeg' %}">
<br>
<p class="m-4 h5">
Ayurvedic medicine promotes internal cleansing for improved health. “Panchakama” is the process of getting rid of food and toxins that interfere with efficient body function. Enemas, oils, and massage therapy help get the body working properly by moving toxins from the tissues to the intestines to remove them from the body.</p>
<h2 class="text-danger m-3">
Overall Balance:</h3>
<img  class="m-4 rounded" src="{% static 'ayurvedasite/images/img8.jpeg' %}">
<br>
<p class="m-4 h5">
The benefit of Ayurveda is that it focuses on individualized treatment and improve the entire body, internally and externally. When someone has emotional stress or health issues, physical activity, nutrition, and spiritual connection can recalibrate your body and promote balance.</p>
<h2 class="text-danger m-3">
Help Cure Insomnia:</h3>
<img  class="m-4 rounded" src="{% static 'ayurvedasite/images/img5.jpeg' %}">
<br>
<p class="m-4 h5">
Having a late dinner, drinking caffeine before bedtime, watching tv, staring at the phone, or eating a spicy or heavy meal for dinner can disrupt your sleep and aggravate your nervous system. Ayurveda can help induce a restful sleep with simple tips like rubbing jasmine or coconut oil on the scalp or soles of feet, drinking a cup of warm almond milk or chamomile tea, or stating a positive affirmation can effectively help cure insomnia and inspire peaceful sleep.</p>
<h2 class="text-danger m-3">
Regulate Bloating:</h3>
<img  class="m-4 rounded" src="{% static 'ayurvedasite/images/img7.jpeg' %}">
<br><p class="m-4 h5">
Practicing Ayurveda can help manage bloating and poor digestion by expelling the buildup of waste. Spices, herbs, and roots like cumin, cardamom, fennel, and ginger can cure indigestion in the body. Chewing cumin and ginger before eating can promote digestion, and drinking cardamom and fennel in boiled water can calm the digestive system as well as relieve cramps.</p>
<h2 class="text-danger m-3">
Healthy and Glowing Skin:</h3>
<img  class="m-4 rounded" src="{% static 'ayurvedasite/images/img6.jpeg' %}">
<br><p class="m-4 h5">
Ayurveda has a ton of proven tricks to help keep your skin soft and radiant without spending money. Consuming veggies like cucumber, lettuce, and daikon radish are easier to digest because of their purifying properties and high-water content. Exercising keeps your joints and muscles toned and helps your body expel toxins through sweat. Nuts and seeds contain healthy fats and Omega-3’s, which have active components responsible for maintaining healthy skin and lowering inflammation in certain skin conditions.
</p>
</h2>
</div>

{% endblock content %}

ayurvedasite/templates/ayurvedasite/symptoms.html
{% extends "ayurvedasite/base.html" %}
{% load static %}


{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center text-info">SYMPTOMS AND REMEDIES</h1>
<div class="row">
	<div class="container">
  
            
            <div class="card text-dark border-info shadow p-3 col-12
            ">
                
               
                    <div card="card-body">
                    	<div class="card-deck shadow">
                    		 {% for symp in sym %}
                    		<div class="card border-dark shadow-lg col-6 p-3 m-2 text-center" id="cards">
                    			<div class="card-body">
                    <h2><div class="card-title text-center text-success">{{ symp.name }}</div></h2>
                    <img src="{{ symp.image.url }}">

                    <p class="card-text"><h3 class="text-danger">Causes</h3>{{ symp.causes|linebreaksbr }}<br>
                    	<h3 class="text-danger">Symptoms</h3>{{symp.symptom|linebreaksbr }}
                    	<h3 class="text-danger">Remedy</h3>{{ symp.remedy|linebreaksbr }}
                    </p>
                
                <br>
                
                   
                  <p class="card-subtitle"><a href="{{ symp.link }}">For More Info</a></p>
</div>
</div>
{% endfor %}                    
            </div>
        </div>
        <div>
        	</div>
       </div>
   


        <br>
            
        <br>
     <div class="pagination m-3">
        
         <span class="step-links">
       
     {% if sym.has_previous %}
     <a class="btn btn-outline-primary" href="?page=1">&laquo;First</a>
     <a class="btn btn-outline-primary" href="?page={{sym.previous_page_number}}">Previous</a>
     {% endif %}
     <span class="step-link">
     <a class="btn btn-primary" href="#">current</a>

 </span>
    
     {% if sym.has_next %}
            <a  class="btn btn-outline-primary" href="?page={{ sym.next_page_number }}">next</a>
            <a class="btn btn-outline-primary" href="?page={{ sym.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
   
    </div>
</div>
 </div>
{% else %}
<div class="container">
	<h1 class="text-danger">You Are Not Logged IN please sign in to Acces the Details</h1>
</div>

{% endif %}
{% endblock content %}